import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, Download, Github, Linkedin, Mail, Menu, X, Cpu, ScanLine, Navigation, Wrench, MoveUpRight, Plus} from 'lucide-react';
import './style.css';
import {Page} from './Pages';
import RobotBoat from './RobotBoat';
import content from './content.json';

const projects = [
 {id:'01',name:'Jaladhi',subtitle:'Autonomous navigation and collision avoidance.',category:'Autonomous systems',image:'jaladhi.jpg',tags:['Autonomous navigation','Collision avoidance','ASV'],text:'An autonomous surface vehicle developed for offshore energy exploration, with navigation and collision avoidance following COLREGs.',role:'Integrated ROS, computer vision, and LiDAR.',result:'2nd place, PENS final project competition.',url:'q_jaladhi',detail:'This final project brings autonomous navigation and maritime collision avoidance into a surface vehicle platform. It connects perception, decision-making, and vehicle control in the context of offshore exploration.'},
 {id:'02',name:'E-AUV · EMOSVER',subtitle:'Autonomous underwater vehicle for KRBAI 2023.',category:'Underwater robotics',image:'emosver.jpg',tags:['AUV','Autonomous missions','Computer vision'],text:'A fully autonomous underwater vehicle built for the Indonesian Underwater Robot Contest (KRBAI) 2023, completing gate navigation and cable-following missions.',role:'Led the team, built the electrical system, and developed autonomous navigation.',result:'2nd place regional, 3rd place national, KRBAI 2023.',url:'f_emosver',detail:'A fully autonomous underwater vehicle for KRBAI 2023. It combines HSV-based lane detection on a Jetson Nano with depth and heading control for mandatory and innovation missions.'},
 {id:'03',name:'ROV · RIG Taurus',subtitle:'Underwater inspection at RIG Taurus.',category:'Field robotics',image:'rov.jpg',tags:['ROV','Underwater inspection','Field operations'],text:'An underwater inspection project with Pertamina Hulu Energi, bringing robotics into offshore operations.',role:'ROV pilot and engineer during offshore inspection.',result:'Completed a 7-day survey at 3 inspection points.',url:'a_rov_taurus',detail:'An underwater inspection deployment at RIG Taurus. The project documents equipment preparation, debugging, field operations, and inspection results in an offshore environment.'},
 {id:'04',name:'Safety Detection',subtitle:'Helmet detection tested in the maintenance area.',category:'Computer vision',image:'safety-detection.jpg',tags:['YOLO','OpenCV','Helmet detection'],role:'Developed the detection and helmet-matching software.',result:'Field tests demonstrated helmet detections and visual warnings.',url:'safety-detection'}
];
const skills=[{icon:ScanLine,name:'Perception',desc:'Image processing and object detection.',items:'Python · OpenCV · YOLO · TensorFlow · Jetson Nano'},{icon:Navigation,name:'Autonomy & control',desc:'Vehicle navigation and motion control.',items:'ROS · MAVLink · PID control · Sensor integration'},{icon:Cpu,name:'Embedded systems',desc:'Firmware, circuit boards, and sensors.',items:'C/C++ · STM32 · ESP32 · PCB design · UART / SPI / I2C'},{icon:Wrench,name:'Field engineering',desc:'Installation, testing, and troubleshooting.',items:'Wiring & panels · Motor drivers · Troubleshooting · Linux'}];
const posts=[['01','ROBOTICS & PURPOSE','Finding Your Ikigai','Jan 08, 2026','2026/finding-your-ikigai-in-robotics/'],['02','ENERGY & EXPLORATION',"Indonesia’s Offshore Renewable Energy Potential",'Dec 28, 2025','2025/energi-terbarukan-lepas-pantai-indonesia/'],['03','COMPUTER VISION','A Complete Guide to YOLOv11 Object Detection','Nov 20, 2025','2025/complete-guide-yolov11-object-detection/']];
function App(){const [path,setPath]=useState(window.location.pathname);
useEffect(()=>{
 const jump=(hash,delay=20,behavior='smooth')=>{if(hash)setTimeout(()=>document.getElementById(decodeURIComponent(hash.slice(1)))?.scrollIntoView({behavior}),delay)};
 const update=()=>{setPath(window.location.pathname);setMenu(false);if(!window.location.hash)window.scrollTo(0,0)};
 const click=e=>{const a=e.target.closest('a');if(!a||a.target==='_blank'||a.hasAttribute('download')||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||e.button!==0)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin||u.pathname.startsWith('/assets/'))return;e.preventDefault();history.pushState({},'',u.pathname+u.search+u.hash);update();jump(u.hash)};
 // A deep link lands before the images have height, so the first jump undershoots.
 // ponytail: re-jump once on load; lazy images further down can still shift layout,
 // give the images intrinsic width/height if that ever shows.
 jump(window.location.hash,60,'instant');
 const settle=()=>jump(window.location.hash,0,'instant');
 if(document.readyState==='complete')setTimeout(settle,300);else window.addEventListener('load',()=>setTimeout(settle,300),{once:true});
 document.addEventListener('click',click);const pop=()=>{update();jump(window.location.hash)};window.addEventListener('popstate',pop);return()=>{document.removeEventListener('click',click);window.removeEventListener('popstate',pop)};
},[]);
useEffect(()=>{const p=content.pages.find(p=>p.path===path);document.title=p?p.title+' | Ansori':path.startsWith('/projects')?'Projects | Ansori':path.startsWith('/blog')?'Journal | Ansori':'Ansori | R&D Robotics Engineer'},[path]);
const [menu,setMenu]=useState(false);
return <><header><a className="brand" href="/#home" aria-label="Ansori home"><span className="brand-mark">a<span>↗</span></span> ansori<span className="brand-period">.</span></a><nav className={menu?'open':''} aria-label="Main navigation">{[['Projects','projects'],['Capabilities','capabilities'],['About','about'],['Journal','journal'],['CV','cv']].map(([name,id])=><a key={id} href={id==='projects'?'/projects/':id==='journal'?'/blog/':id==='cv'?'/cv/':'/#'+id} onClick={()=>setMenu(false)}>{name}</a>)}</nav><a className="header-contact" href="mailto:achadansori@gmail.com">Contact <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main>{path!=='/'?<Page key={path} path={path}/>:<><section className="hero wrap" id="home"><div className="hero-copy"><div className="eyebrow"><span className="tiny-cross">+</span> R&D ROBOTICS ENGINEER AT PT ALDZAMA <span className="small-rule"/></div><h1>Muhammad<br/><span>Achad Ansori.</span></h1><p className="hero-role">R&D Robotics Engineer</p><p className="hero-description">I develop embedded systems and work on autonomous navigation, computer vision, and industrial robotics.</p><div className="hero-actions"><a className="button primary" href="#projects">View projects <ArrowUpRight size={19}/></a><a className="button secondary" href="/assets/pdf/cv_muhammad_achad_ansori.pdf" download><Download size={18}/> Download CV</a></div><div className="hero-foot"><span>ROBOTICS</span><span>EMBEDDED SYSTEMS</span><span>APPLIED AI</span></div></div><div className="portrait"><img src="/images/portrait.jpg" alt="Ansori wearing field safety equipment at sea" loading="lazy"/><div className="portrait-label"><span>MUHAMMAD ACHAD ANSORI</span><ArrowUpRight size={20}/></div></div></section>
<section className="wrap section about" id="about"><div className="about-heading"><div className="eyebrow">01 / ABOUT ME</div><h2>About me<span>.</span></h2></div><div className="about-copy"><p>I am an R&D Robotics Engineer at PT Aldzama, specializing in embedded systems, robotics, and industrial automation. I hold a Bachelor of Applied Science in Electronics Engineering from Politeknik Elektronika Negeri Surabaya (PENS).</p><p>My experience spans robotics engineering, from embedded programming, PCB design, and control systems to computer vision, IoT, and autonomous navigation. I have worked across marine robotics, offshore operations, smart manufacturing, aquaculture technology, and demolition robotics.</p><p>I work with both hardware and software, turning prototypes into systems that can be used in the field. My work includes control systems, AI inspection on edge devices, and production panel wiring.</p><p className="ikigai">My ikigai is in robotics, where my technical skills, passion, and purpose converge. I am fascinated by how robotics bridges multiple disciplines to create intelligent systems that extend human capabilities beyond physical and cognitive limitations. I aspire to grow as a full-stack robotics engineer, advancing systems that bring meaningful impact to industry and society.</p><a className="text-link" href="/cv/">Experience & CV <ArrowUpRight size={18}/></a></div></section>
<RobotBoat/>
<div className="discipline-strip"><div className="wrap"><span>ROBOTICS DEVELOPMENT</span><span>Perceive <Plus/> Plan <Plus/> Control <Plus/> Deploy</span></div></div>
<section className="wrap section" id="projects"><div className="section-heading"><div><div className="eyebrow">02 / SELECTED WORK</div><h2>Selected projects<span>.</span></h2></div><p>Autonomous vehicles, underwater inspection, and computer vision projects.</p></div><div className="projects">{projects.map(p=><button className="project" key={p.id} onClick={()=>{history.pushState({},'', '/projects/'+p.url+'/');setPath('/projects/'+p.url+'/');window.scrollTo(0,0)}} aria-label={'View project: '+p.name}><div className="project-image"><img src={'/images/'+p.image} alt={p.name+' project'} loading="lazy"/><span className="project-number">/{p.id}</span><span className="project-arrow"><ArrowUpRight/></span></div><div className="project-category">{p.category}</div><h3>{p.name}</h3><p>{p.subtitle}</p><dl className="project-facts"><div><dt>My contribution</dt><dd>{p.role}</dd></div><div><dt>Result</dt><dd>{p.result}</dd></div></dl><div className="project-tags">{p.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div></button>)}</div><a className="text-link all-projects" href="/projects/">All projects <ArrowUpRight size={18}/></a></section>
<section className="capabilities" id="capabilities"><div className="wrap section"><div className="section-heading"><div><div className="eyebrow">03 / SKILLS</div><h2>Technical skills<span>.</span></h2></div><div className="stack-note"><span>HARDWARE</span><div>←────────→</div><span>SOFTWARE</span></div></div><div className="skills">{skills.map((s,i)=><article key={s.name}><div className="skill-top"><s.icon size={28} strokeWidth={1.3}/><span>0{i+1}</span></div><h3>{s.name}</h3><p>{s.desc}</p><small>{s.items}</small></article>)}</div></div></section>

<section className="wrap section journal" id="journal"><div className="section-heading"><div><div className="eyebrow">04 / ARTICLES</div><h2>Recent articles<span>.</span></h2></div><a className="text-link" href="/blog/">All articles <ArrowUpRight size={18}/></a></div><div>{posts.map(([n,cat,title,date,path])=><a className="post" key={n} href={'/blog/'+path}><span className="post-number">{n}</span><div><span className="post-category">{cat}</span><h3>{title}</h3></div><time>{date}</time><ArrowUpRight size={24}/></a>)}</div></section>
<section className="contact wrap" id="contact"><div className="eyebrow">CONTACT</div><div className="contact-main"><h2>Get in touch<span>.</span></h2><a className="contact-arrow" href="mailto:achadansori@gmail.com" aria-label="Email Ansori"><MoveUpRight size={58} strokeWidth={1}/></a></div><a className="email" href="mailto:achadansori@gmail.com">achadansori@gmail.com <ArrowUpRight size={22}/></a></section></>}</main><footer className="wrap"><a className="brand" href="/#home">ansori.</a><span>© {new Date().getFullYear()} Muhammad Achad Ansori</span><div><a href="https://github.com/achadansori" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><a href="https://linkedin.com/in/achadansori" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href="https://www.instagram.com/achadansori/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={14}/></a><a href="/#home" aria-label="Back to top">Back to top ↑</a></div></footer>
</>}

createRoot(document.getElementById('root')).render(<App/>);
