import React, {useState} from 'react';
import {ArrowUpRight, ArrowLeft, Search, Download} from 'lucide-react';
import content from './content.json';
export function Page({path}) {
 const [query,setQuery]=useState('');
 const normalized=path.endsWith('/')?path:path+'/';
 const page=content.pages.find(p=>p.path===normalized);
 const projectIndex=normalized==='/projects/';
 const blogIndex=normalized.startsWith('/blog/')&&!page;
 if(projectIndex||blogIndex){
  const type=projectIndex?'project':'article';
  const archive=normalized!=='/blog/'&&blogIndex?normalized:null;
  const pages=content.pages.filter(p=>p.type===type && (!archive || p.path.startsWith(archive) || p.archives?.includes(archive)) && (p.title+' '+p.description).toLowerCase().includes(query.toLowerCase()));
  return <section className="wrap section library"><a className="text-link" href="/"><ArrowLeft size={17}/> Back home</a><div className="section-heading"><div><div className="eyebrow">{projectIndex?'PROJECTS':'ARTICLES'}</div><h1>{projectIndex?'Projects':'Articles'}</h1><p>{projectIndex?'Projects from university competitions, research, and industrial deployments.':'My writing on robotics, computer vision, energy, and career.'}</p></div></div><label className="search-field"><Search size={19}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={projectIndex?'Search projects…':'Search articles…'} aria-label={projectIndex?'Search projects':'Search articles'}/><span>{pages.length} {projectIndex?'projects':'articles'}</span></label><div className={projectIndex?'projects library-grid':'article-list'}>{pages.map((p,i)=><a href={p.path} className={projectIndex?'project':'article-card'} key={p.path}>{projectIndex&&<div className="project-image">{p.image&&<img src={p.image} alt={p.title} loading="lazy"/>}<span className="project-number">/{String(i+1).padStart(2,'0')}</span><span className="project-arrow"><ArrowUpRight/></span></div>}<div className="project-category">{projectIndex?'ROBOTICS & ENGINEERING':p.path.split('/')[2]}</div><h3>{p.title}</h3><p>{p.description}</p>{!projectIndex&&<span className="text-link">Read article <ArrowUpRight size={16}/></span>}</a>)}</div>{!pages.length&&<p className="empty-message">No matches. Try another keyword.</p>}</section>
 }
 if(page)return <section className="wrap section reading-page"><a className="text-link" href={page.type==='project'?'/projects/':page.type==='article'?'/blog/':'/'}><ArrowLeft size={17}/> {page.type==='project'?'All projects':page.type==='article'?'All articles':'Back home'}</a><div className="reading-heading"><div className="eyebrow">{page.type==='project'?'PROJECT DOCUMENTATION':page.type==='article'?'ENGINEERING JOURNAL':'EXPERIENCE & EDUCATION'}</div><h1>{page.title}</h1>{page.description&&<p>{page.description}</p>}{page.archives?.length>0&&<div className="project-tags">{page.archives.filter(a=>a.includes('/tag/')).map(a=><a key={a} href={a}><span>{a.split('/').filter(Boolean).at(-1).replaceAll('-',' ')}</span></a>)}</div>}{page.type==='cv'&&content.resume.map(url=><a key={url} className="button primary" href={url} download><Download size={18}/> Download CV</a>)}</div><div className={'prose '+(page.type==='cv'?'resume-content':'')} dangerouslySetInnerHTML={{__html:page.html}}/><div className="reading-end"><a className="text-link" href={page.type==='project'?'/projects/':page.type==='article'?'/blog/':'/'}><ArrowLeft size={17}/> Back to overview</a><a className="text-link" href="mailto:achadansori@gmail.com">Contact me <ArrowUpRight size={17}/></a></div></section>;
 return <section className="wrap section"><div className="eyebrow">404</div><h1>Page not found.</h1><a className="button primary" href="/">Back home <ArrowUpRight size={18}/></a></section>
}
